/**
 * @file NetworkingDefines.h
 * @author Nils Henrich
 * @brief Basic definitions for the network client
 * @version 1.0
 * @date 2021-12-28
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#ifndef NETWORKINGDEFINES_H_INCLUDED
#define NETWORKINGDEFINES_H_INCLUDED

namespace networking
{
    enum : int
    {
        NETWORKCLIENT_START_OK = 0,
        NETWORKCLIENT_ERROR_START_SET_CONTEXT = 10,
        NETWORKCLIENT_ERROR_START_WRONG_CA_PATH = 20,
        NETWORKCLIENT_ERROR_START_WRONG_CERT_PATH = 21,
        NETWORKCLIENT_ERROR_START_WRONG_KEY_PATH = 22,
        NETWORKCLIENT_ERROR_START_WRONG_KEY = 23,
        NETWORKCLIENT_ERROR_START_CREATE_SOCKET = 30,
        NETWORKCLIENT_ERROR_START_SET_SOCKET_OPT = 31,
        NETWORKCLIENT_ERROR_START_CONNECT = 40,
        NETWORKCLIENT_ERROR_START_DO_HANDSHAKE = 50,
        NETWORKCLIENT_ERROR_START_VERIFY_HANDSHAKE = 51
    };

    enum : char
    {
        NETWORKCLIENT_CHAR_TRANSFER_START = '\x02',
        NETWORKCLIENT_CHAR_TRANSFER_END = '\x03'
    };
}

#endif // NETWORKINGDEFINES_H_INCLUDED
