#ifndef NETWORKINGDEFINES_H_INCLUDED
#define NETWORKINGDEFINES_H_INCLUDED

// Error Codes bei Client Start
enum: int
{
    TLSCLIENT_START_OK                      = 0,
    TLSCLIENT_ERROR_START_WRONG_PORT        = 10,
    TLSCLIENT_ERROR_START_SET_CONTEXT       = 20,
    TLSCLIENT_ERROR_START_WRONG_CA_PATH     = 30,
    TLSCLIENT_ERROR_START_WRONG_CERT_PATH   = 31,
    TLSCLIENT_ERROR_START_WRONG_KEY_PATH    = 32,
    TLSCLIENT_ERROR_START_WRONG_KEY         = 33,
    TLSCLIENT_ERROR_START_CREATE_BIO        = 40,
    TLSCLIENT_ERROR_START_DO_HANDSHAKE      = 50,
    TLSCLIENT_ERROR_START_VERIFY_HANDSHAKE  = 51
};


#endif // NETWORKINGDEFINES_H_INCLUDED
